services:
  intershop:
    image: intershop/main
    build:
      context: application
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - payment
      - cache

  payment:
    image: intershop/payment
    build:
      context: payment
      dockerfile: ./Dockerfile

  cache:
    image: redis:7-alpine
