services:
  intershop:
    image: intershop/main
    build:
      context: application
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - cache
      - keycloak
      - payment

  payment:
    image: intershop/payment
    build:
      context: payment
      dockerfile: ./Dockerfile
    depends_on:
      keycloak:
        condition: service_healthy

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    container_name: keycloak
    ports:
      - "8082:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    command:
      - start-dev
      - --import-realm
      - /opt/keycloak/data/import/realm-export.json

    volumes:
      - ./realms:/opt/keycloak/data/import

    healthcheck:
      test: [
        "CMD-SHELL",
        'exec 3<>/dev/tcp/localhost/8080; echo -e "GET /health/ready HTTP/1.1\nhost: localhost:8080\n" >&3; timeout --preserve-status 1 cat <&3 | grep -m 1 status | grep -m 1 UP; ERROR=$?; exec 3<&-; exec 3>&-; exit $ERROR'
      ]
      interval: 10s
      timeout: 5s
      retries: 3

  cache:
    image: redis:7-alpine
